spring:
  jpa:
    hibernate.ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
  datasource: 
    url: jdbc:h2:tcp://192.168.1.182:9092
    driverClassName: org.h2.Driver
    username: admin 
    password: admin
