spring:
  jpa:
    hibernate.ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
  datasource: 
    url: jdbc:h2:file:/C:/workspace/bd/fornecedor.db
    driverClassName: org.h2.Driver
    username: admin 
    password: admin
